# Generated by Django 4.1.4 on 2022-12-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Card Baslik')),
                ('text', models.TextField(verbose_name='Card Yazisi')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='Card Resmi')),
                ('priece', models.IntegerField(null=True, verbose_name='urun fiyati')),
                ('date_now', models.DateTimeField(verbose_name='Paylasim Zamani')),
            ],
        ),
    ]
