# Generated by Django 4.1.4 on 2022-12-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProje', '0002_categori_card_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='priece',
            new_name='price',
        ),
    ]
