# Generated by Django 4.1.4 on 2023-01-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProje', '0004_card_user_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylasim Zamani'),
        ),
        migrations.CreateModel(
            name='Shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(verbose_name='Adet')),
                ('fiyat', models.FloatField(verbose_name='Toplam Fiyat')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProje.card', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
        ),
    ]
